name: 🚀 Deploy manual

on: push

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ env.FTP_HOST }}
        username: ${{ env.FTP_USER }}
        password: ${{ env.FTP_PASS }}
        server-dir: public_html/www/